language: ruby
rvm: system
cache:
  directories:
    - $HOME/.gem/ruby
    - $HOME/Library/Caches/Homebrew/style
    - $HOME/Library/Caches/Homebrew/tests
branches:
  only:
    - master
matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode9
    - os: linux
      sudo: false

script:
  - env | grep GIT_ASKPASS
  - env | sed 's/=.*//g' | sort

notifications:
  slack: machomebrew:1XNF7p1JRCdBUuKaeSwsWEc1
