jobs:
- job: macOS
  pool:
    vmImage: macOS-10.13
  steps:
    - bash: |
        set -e
        env | grep -io '.*TOKEN='

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
    - bash: |
        set -e
        env | grep -io '.*TOKEN='
