name: GitHub Actions CI
on:
  - push
  - pull_request
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: OUTPUT
        run: echo TEST_OUTPUT
